<?php
  echo("<!DOCTYPE html>\r\n");
  echo("<html lang=\"en\">\r\n");
  echo("<body>\r\n");
  echo("This is some test HTML generated by TestEcho.php");
  echo("</body>\r\n");
  echo("</html>\r\n");
?>