<?php
  //echo("<!DOCTYPE html>\r\n");
  //echo("<html lang=\"en\">\r\n");
  //echo("<body>\r\n");
  //echo("This is some test HTML generated by TestEcho.php");
  //echo("</body>\r\n");
  //echo("</html>\r\n");

  Line("<!DOCTYPE html>");
  Line("<html lang=\"en\">");
  Line("<body>");
  Line("  This is some test HTML generated by TestEcho.php<br />");
  Line("</body>");
  Line("</html>");

  // Encode to HTML entities.
  function Display(string $text) : string
  {
    $retValue = htmlspecialchars($text);
    return $retValue;
  }

  // Writes the supplied text to the output stream with the new line values.
  function Line(?string $text = null, ?bool $display = false
    , ?bool $lastPre = false)
  {
    if ($display)
    {
      $text = Display($text);
    }
    if ($lastPre)
    {
     $text = $text . "</pre>");
    }
    echo($text . "\r\n");
  }
?>